# Generated by Django 4.0 on 2022-01-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_niko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
