# Generated by Django 4.0 on 2022-01-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('method', models.CharField(max_length=200)),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
